### PR TITLE
Mapping Kleisli on old GHC

### PR DESCRIPTION
**Pull request by treeowl**
Write a custom implementation of `roam` for `Kleisli m` even on
old GHC versions.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Possibly silly question: could we avoid the use of CPP if we used the `WrappedMonad` code path everywhere?

**Comment by treeowl** [comment]
I think so, but it's quite a wart. I used the CPP so the whole thing will vanish in a puff of cleanup whenever (if ever) GHC 7.8 moves out of the support window.

**Comment by RyanGlScott** [comment]
OK. In that case, could you leave a brief comment explaining why CPP is used here, and that it should be revisited in the future? Other than that, LGTM.

**Comment by treeowl** [comment]
Also, there's been at least some talk about eventually deprecating `WrappedMonad`, now that Monad of no return is in progress.

**Comment by treeowl** [comment]
I'll add a comment to explain. The future revisit will presumably be automatic when someone starts searching for `MIN_VERSION_base` to change the support window, so I won't mention that separately.

**Comment by treeowl** [comment]
@RyanGlScott Done!

**Pull request merged**
